# vim :set ts=2 sw=2 sts=2 et :
---
language: python
cache: pip

sudo: false

matrix:
  include:
    - env: TOXENV=py34-dj111
      python: 3.4
    - env: TOXENV=py35-dj111
      python: 3.5
    - env: TOXENV=py36-dj111
      python: 3.6
    - env: TOXENV=py34-dj20
      python: 3.4
    - env: TOXENV=py35-dj20
      python: 3.5
    - env: TOXENV=py36-dj20
      python: 3.6
    - env: TOXENV=flake8
    - env: TOXENV=isort

install:
  - pip install tox

script:
  - tox
